import "./globals.css"
import { Outfit } from "next/font/google"
import Image from "next/image"
import Link from "next/link"
import { useRouter } from "next/router"
import { ClerkProvider } from "@clerk/nextjs/app-beta"

import { NavBar } from "@/components/NavBar"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <main
            className={`${outfit.className} grid grid-rows-[56px_auto] md:grid-rows-[72px_auto] lg:grid-cols-[128px_auto] grid-cols-1 lg:grid-rows-1 bg-custom-bue-900 h-screen`}
          >
            <div className="md:p-6 lg:p-0 lg:h-full lg:py-8 lg:pl-8">
              <NavBar />
            </div>
            <main className="">{children}</main>
          </main>
        </body>
      </ClerkProvider>
    </html>
  )
}
